# Generated by Django 5.2.16 on 2026-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_document_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='chunk_count',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
