# Generated by Django 5.2.16 on 2026-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_chunk_chunk_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='chunk_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
