# Generated by Django 5.2.16 on 2026-07-25 15:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_remove_chunk_chunk_count_document_chunk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ingestion_c_search__8552a9_gin'),
        ),
    ]
