# Generated by Django 5.2.16 on 2026-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_chunk_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Oʻzbekcha'), ('ru', 'Русский')], default='en', help_text='Botga yuklangan hujjatlar va javoblar tili', max_length=10),
        ),
    ]
