# Generated by Django 5.2.16 on 2026-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_completion_tokens_message_prompt_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
