# Generated by Django 5.2.16 on 2026-07-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_group_mode', models.BooleanField(default=False)),
                ('website_enabled', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('uses_rag', models.BooleanField(default=True)),
                ('api_key_source', models.CharField(choices=[('platform', 'Platforma key (static)'), ('client', "Client o'z key'ini kiritadi")], default='platform', max_length=20)),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic (Claude)')], default='openai', max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100, null=True)),
                ('milvus_collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('system_prompt', models.TextField(blank=True)),
                ('welcome_message', models.CharField(blank=True, max_length=500)),
                ('fallback_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='clients.client')),
            ],
        ),
    ]
