# Generated by Django 5.2.16 on 2026-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='client_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
