# Generated by Django 5.2.16 on 2026-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_bot_client_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='default_top_k',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='bot',
            name='api_key_source',
            field=models.CharField(choices=[('platform', 'Platforma key'), ('client', "Client o'z key'ini kiritadi")], default='platform', max_length=20),
        ),
    ]
