# Generated by Django 5.2.16 on 2026-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_bot_default_top_k_alter_bot_api_key_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='relevance_criteria',
            field=models.TextField(blank=True, help_text="Guruhda qaysi mavzudagi savollarga javob berish kerakligini tavsiflang. Masalan: 'mahsulot narxi, yetkazib berish, mavjudligi haqida savollar'"),
        ),
    ]
