# Generated by Django 5.2.16 on 2026-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_bot_relevance_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='similarity_threshold',
            field=models.FloatField(default=0.3, help_text="0 dan 1 gacha. Past qiymat = ko'proq natija qabul qilinadi."),
        ),
    ]
