# Generated by Django 5.2.16 on 2026-07-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_bot_similarity_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='similarity_threshold',
        ),
    ]
