# Generated by Django 5.2.16 on 2026-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_bot_similarity_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic (Claude)'), ('deepseek', 'DeepSeek')], default='openai', max_length=20),
        ),
    ]
