# Generated by Django 5.2.16 on 2026-07-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_bot_llm_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='default_top_k',
        ),
    ]
