# Generated by Django 5.2.16 on 2026-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_bot_default_top_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic (Claude)'), ('deepseek', 'DeepSeek'), ('cloudapi', 'CloudAPI.uz')], default='openai', max_length=20),
        ),
    ]
