# Generated by Django 5.2.16 on 2026-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_bot_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='term_frequencies',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
