# Generated by Django 5.2.16 on 2026-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_bot_term_frequencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='embedding_model',
            field=models.CharField(blank=True, choices=[('local', 'Local (bepul, sentence-transformers)'), ('text-embedding-3-small', 'OpenAI text-embedding-3-small'), ('text-embedding-3-large', 'OpenAI text-embedding-3-large'), ('gemini', 'Google Gemini (gemini-embedding-001)')], default='local', max_length=100),
        ),
    ]
