# Generated by Django 5.2.16 on 2026-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
    ]
