# Generated by Django 5.2.16 on 2026-07-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_document_chunk_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
